runtime: python39

entrypoint: gunicorn -w 4 -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "qwiklabs-gcp-02-aafa89bc4ad3"  # Replace with your actual project ID
  DATASET_ID: "qwiklabs-gcp-02-aafa89bc4ad3.customerdata"            # Replace with your actual dataset ID

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
