runtime: python39

entrypoint: gunicorn -w 4 -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "qwiklabs-gcp-02-aafa89bc4ad3"
  DATASET_ID: "qwiklabs-gcp-02-aafa89bc4ad3.customerdata"
  PORT: "8080"

service: my-app  # Replace with your app's name

instance_class: F1  # You can adjust the instance class for memory/CPU needs

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
